app/routes.py
from flask import Blueprint, flash, jsonify, render_template, request
from flask_login import current_user, login_required

from app.models import UserSubscription
from backend.database import db
from backend.email_management.send_support import send_simple_message
from backend.repository import (
    ChannelRepository,
    CustomQueryRepository,
    UserSubscriptionRepository,
    VideoCategoryRepository,
)
from backend.service import ApiService

main_bp = Blueprint("main", __name__)


@main_bp.route("/")
def index():
    return render_template("index.html", title="Home")


@main_bp.route("/dashboard")
@login_required
def dashboard():
    if current_user.is_authenticated and current_user.youtube_credentials:
        # Initialize repositories
        customqueryrepository = CustomQueryRepository()
        videocategoryrepository = VideoCategoryRepository()

        # Get the top 5 countries of the user's subscriptions
        top_5_countries = customqueryrepository.get_top_5_countries(
            current_user.user_id
        )
        # Create a list of dictionaries containing the custom data
        custom_data = [
            {"label": row.country, "value": row.count} for row in top_5_countries
        ]

        # Fetch category reference table
        video_categories = videocategoryrepository.get_video_category_list()
        if len(video_categories) == 0:
            api_service = ApiService(current_user)
            api_service.save_video_categories(api_service.get_video_categories())

            # Fetch channels in need of categorization and update the calculated category field
            # api_service = ApiService(current_user)
            # api_service.update_channel_calculated_category()

        print(
            customqueryrepository.get_subscription_categorie_count(current_user.user_id)
        )

        # Get the number of subscriptions per category
        labels, data = customqueryrepository.get_subscription_categorie_count(
            current_user.user_id
        )

    return render_template(
        "dashboard.html",
        custom_data=custom_data,
        labels=labels,
        data=data,
        username=current_user.username,
    )


@main_bp.route("/yourpicks")
@login_required
def yourpicks():
    if current_user.is_authenticated and current_user.youtube_credentials:
        usersubscriptionrepository = UserSubscriptionRepository()
        channelrepository = ChannelRepository()

        # Get all the UserSubscription objects that belong to the current user
        user_subscriptions = (
            usersubscriptionrepository.get_user_subscription_list_enriched(
                current_user.user_id
            )
        )
        print(user_subscriptions[0])

        # If there are no UserSubscription objects, fetch the user's subscriptions and the channels from the API
        if len(user_subscriptions) == 0:
            api_service = ApiService(current_user)
            # get and save the user's subscriptions from the YouTube API
            user_subscriptions = api_service.get_user_subscriptions()
            api_service.save_user_subscriptions(user_subscriptions)

            # extract the channel IDs from the subscriptions
            channel_ids = [
                user_subscription["snippet"]["resourceId"]["channelId"]
                for user_subscription in user_subscriptions
            ]
            # fetch their channel details from the YouTube API
            api_service.save_channel(api_service.get_channel(channel_ids))

            # get the enriched UserSubscription objects from the database using the current user's ID
            user_subscriptions = (
                usersubscriptionrepository.get_user_subscription_list_enriched(
                    current_user.user_id
                )
            )

        elif len(user_subscriptions) > 0:
            # Get the user's subscriptions
            user_subscriptions = (
                usersubscriptionrepository.get_user_subscription_list_enriched(
                    current_user.user_id
                )
            )

            # Fetch the user's subscription list from the API
            api_service = ApiService(current_user)
            user_subscriptions_api = api_service.get_user_subscriptions()

            # Create lists to store channel IDs from local and API sources
            local_channel_ids = [
                user_subscription.channel_id for user_subscription in user_subscriptions
            ]
            api_channel_ids = [
                user_subscription["snippet"]["resourceId"]["channelId"]
                for user_subscription in user_subscriptions_api
            ]

            # Find new channel IDs in the API response
            new_channel_ids = list(set(api_channel_ids) - set(local_channel_ids))

            # Save the new subscriptions to the local database
            api_service.save_user_subscriptions(user_subscriptions_api)

            # Fetch the new channel subscriptions
            new_subscriptions_channel = api_service.get_channel(new_channel_ids)
            api_service.save_channel(new_subscriptions_channel)

            # get the enriched UserSubscription objects from the database using the current user's ID
            user_subscriptions = (
                usersubscriptionrepository.get_user_subscription_list_enriched(
                    current_user.user_id
                )
            )

    return render_template("yourpicks.html", user_subscriptions=user_subscriptions)


@main_bp.route("/update_subscription_visibility", methods=["POST"])
def update_subscription_visibility():
    print("aaa")
    user_subscription_id = request.form["user_subscription_id"]
    visibility = request.form["visibility"]
    visibility = True if visibility == "true" else False

    print(user_subscription_id, visibility)
    user_subscription = UserSubscription.query.filter_by(
        user_subscription_id=user_subscription_id
    ).first()

    if user_subscription:
        user_subscription.flag_is_visible = visibility
        db.session.commit()
        return jsonify({"success": True})
    else:
        return jsonify({"success": False})


@main_bp.route("/yourtimeline")
@login_required
def yourtimeline():
    if current_user.is_authenticated and current_user.youtube_credentials:
        # Initialize repositories
        usersubscriptionrepository = UserSubscriptionRepository()
        customqueryrepository = CustomQueryRepository()

        # Get all the UserSubscription objects that belong to the current user
        user_subscriptions = usersubscriptionrepository.get_user_subscription_list(
            current_user.user_id
        )
        # Get the first subscription's and calculate the difference between the current time and the subscription's time
        diff_time = customqueryrepository.diff_now_date(
            usersubscriptionrepository.get_oldest_user_subcription_date(
                current_user.user_id
            )
        )
    return render_template(
        "yourtimeline.html",
        user_subscriptions=user_subscriptions,
        diff_time=diff_time,
    )


@main_bp.route("/support")
@login_required
def support():
    return render_template("support.html", email=current_user.email)


@main_bp.route("/send_message", methods=["GET", "POST"])
def send_message():
    subject = request.form["subject"]
    email = request.form["email"]
    message = request.form["message"]

    if request.method == "POST":
        response = send_simple_message(subject, email, message)
        if response.status_code == 200:
            flash("Message sent successfully!", "success")
        else:
            flash("Error sending message.", "error")
        return render_template("support.html")
    return render_template("support.html")

app/templates/dashboard.html
{% extends "base.html" %} {% block content %}

<div class="bg-white-100">
  <section class="container mx-auto">
    <section class="p-10 h-screen">
      <div class="py-2">
        <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-center text-green-600 dark:text-green-600">
          Dashboard
        </h2>
      </div>

      <div class="overflow-hidden w-1/2 mx-auto text-center">
        <p class="mb-2 lg:mb-2 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl">
          What country are the Channels you are watching from ?
        </p>
        <p class="mt-2 mb-2 lg:mb-16 font-light text-center text-gray-500 dark:text-gray-400 sm:text-sm">(this is the
          country of origin where the channel was set up)</p>
        <canvas class="p-2" id="chartDoughnut"></canvas>
      </div>

      <!-- Required chart.js -->
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

      <!-- Chart doughnut -->
      <script src="../static/js/doughnut_chart_dashboard.js"></script>
      <script>
        const customData = {{ custom_data | tojson }};
        createDoughnutChart(customData);
      </script>


      <!-- Radar chart -->
      <script src="../static/js/radar_chart_dashboard.js"></script>

      <div class="overflow-hidden w-3/5 mx-auto text-center">
        <p id="spider_chart"
          class="mt-20 mb-2 lg:mb-2 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl">
          Let's see what you are into watching in terms of channel categories. </p>
        <p class="mt-2 mb-2 lg:mb-16 font-light text-center text-gray-500 dark:text-gray-400 sm:text-sm">(channel
          category is not a thing, it's been
          deduce from the categories of the top videos of each channel)</p>
        <canvas id="radar_chart"></canvas>
        <script>
          createChart({{ labels| tojson }}, {{ data| tojson }}, {{ username| tojson }});
        </script>
      </div>

      {% endblock %}
    </section>
  </section>
</div>

app/templates/index.html
{% extends "base.html" %} {% block content %}

<div class="bg-white-100">
  <section class="container mx-auto">
    <section class="p-10 h-screen">
      <div class="py-2">
        <div class="flex items-center justify-center mb-6">
          <span
            class="bg-green-600 text-white text-xs font-medium mr-2 mb-4 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300"
            >Hand-Picked</span
          >
        </div>
        <h2
          class="mb-4 text-4xl tracking-tight font-extrabold text-center text-green-400 dark:text-green-400"
        >
          From Solo to Social...
        </h2>
        <h2
          class="mb-16 text-4xl tracking-tight font-extrabold text-center text-green-600 dark:text-green-600"
        >
          Making Youtube a multiplayer experience
        </h2>
        <p
          class="mb-16 lg:mb-8 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl"
        >
          Share the curated, hand-picked subscription list you've built with the
          world. Uncover hidden gems with the help of your friends. Take a trip
          down memory lane and revisit your entire content history.
        </p>
        <div class="flex items-center justify-center">
          <button
            class="bg-green-600 hover:bg-green-600 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            type="submit"
            onclick="window.location.href='/signin'"
          >
            Try it out!
          </button>
        </div>
        <div class="flex items-center justify-center mt-10">
          <iframe
            style="border-radius: 20px; overflow: hidden; z-index: 1"
            src="https://www.youtube.com/embed/ZXni9_91ORs?start=0?autoplay=1"
            frameborder="0"
            allow="autoplay; fullscreen"
            width="680"
            height="360"
            allowfullscreen
          ></iframe>
        </div>
      </div>
    </section>
  </section>
</div>
{% endblock %}

app/templates/signin.html
{% extends "base.html" %} {% block content %}
<section class="bg-white">
  <div class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
    <h2
      class="mb-4 text-4xl tracking-tight font-extrabold text-center text-green-600 dark:text-green-600"
    >
      Sign In
    </h2>
    <p
      class="mb-8 lg:mb-16 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl"
    >
      Found a bug? Want to send feedback? Feel free to contact me.
    </p>

    <!-- <div class="w-full max-w-xs"> -->
      <form method="POST" class="bg-white rounded px-8 pt-6 pb-8 mb-4">
        {{ form.hidden_tag() }}

        <div class="mb-4">
          <label class="block text-gray-700 text-sm font-bold mb-2" for="email">
            Email
          </label>
          <input
            class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
            id="email"
            name="email"
            type="text"
            placeholder="Email"
          />
        </div>
        <div class="mb-6">
          <label
            class="block text-gray-700 text-sm font-bold mb-2"
            for="password"
          >
            Password
          </label>
          <input
            class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
            id="password"
            name="password"
            type="password"
            placeholder="*********"
          />
        </div>
        <div class="flex items-center justify-between">
          <button
            class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            type="submit"
          >
            Sign In
          </button>
        </div>
      </form>
    </div>

    {% include 'components/flash_messages.html' %} {% endblock %}
  </div>
</section>

app/templates/signup.html
{% extends "base.html" %} {% block content %}

<section class="bg-white">
  <div class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
    <h2
      class="mb-4 text-4xl tracking-tight font-extrabold text-center text-green-600 dark:text-green-600"
    >
      Sign Up
    </h2>
    <p
      class="mb-8 lg:mb-16 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl"
    >
      Found a bug? Want to send feedback? Feel free to contact me.
    </p>

    <!-- <div class="w-full max-w-xs"> -->
      <form method="POST" class="bg-white rounded px-8 pt-6 pb-8 mb-4">
        {{ form.hidden_tag() }}
        <!--pass csrf token to secure post -->
        <div class="mb-4">
          <label
            class="block text-gray-700 text-sm font-bold mb-2"
            for="username"
          >
            Username
          </label>
          <input
            class="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
            id="username"
            name="username"
            type="text"
            placeholder="Username"
          />
        </div>
        <div class="mb-4">
          <label class="block text-gray-700 text-sm font-bold mb-2" for="email">
            Email
          </label>
          <input
            class="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
            id="email"
            name="email"
            type="text"
            placeholder="Email"
          />
        </div>
        <div class="mb-4">
          <label
            class="block text-gray-700 text-sm font-bold mb-2"
            for="password"
          >
            Password
          </label>
          <input
            class="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
            id="password"
            name="password"
            type="password"
            placeholder="*********"
          />
        </div>
        <div class="mb-6">
          <label
            class="block text-gray-700 text-sm font-bold mb-2"
            for="password2"
          >
            Repeat password
          </label>
          <input
            class="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
            id="password2"
            name="password2"
            type="password"
            placeholder="*********"
          />
        </div>
        <div class="flex items-center justify-between">
          <button
            class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            type="submit"
          >
            Sign Up
          </button>
        </div>
      </form>
    </div>

    {% include 'components/flash_messages.html' %} {% endblock %}
  </div>
</section>

app/templates/support.html
{% extends "base.html" %} {% block content %}
<section class="bg-white">
  <div class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
    <h2
      class="mb-4 text-4xl tracking-tight font-extrabold text-center text-green-600 dark:text-green-600"
    >
      Support
    </h2>
    <p
      class="mb-8 lg:mb-16 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl"
    >
      Found a bug? Want to send feedback? Feel free to contact me.
    </p>
    <form
      action="{{ url_for('main.send_message') }}"
      method="POST"
      class="space-y-8"
    >
      <div>
        <label for="email" class="block text-gray-700 text-sm font-bold mb-2"
          >Your email</label
        >
        <input
          type="email"
          id="email"
          name="email"
          class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
          value="{{ email }}"
          placeholder="your@email.com"
          required
        />
      </div>
      <div>
        <label for="subject" class="block text-gray-700 text-sm font-bold mb-2"
          >Subject</label
        >
        <input
          type="text"
          id="subject"
          name="subject"
          class="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
          placeholder="Let me know how I can help you"
          required
        />
      </div>
      <div class="sm:col-span-2">
        <label for="message" class="block text-gray-700 text-sm font-bold mb-2"
          >Your message</label
        >
        <textarea
          id="message"
          name="message"
          rows="6"
          class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
          placeholder="Leave a comment..."
        ></textarea>
      </div>
      <button
        type="submit"
        class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
      >
        Send message
      </button>
    </form>
  </div>
</section>
{% include 'components/flash_messages.html' %} {% endblock %}

app/templates/yourtimeline.html
{% extends "base.html" %} {% block content %}

<div class="bg-white-100">
  <section class="container mx-auto">
    <section class="p-10 h-screen">
      <div class="py-2">
        <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-center text-green-600 dark:text-green-600">
          Your Timeline
        </h2>
        <p class="mb-8 lg:mb-4 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl">
          A brief history of time. This is who you started watching at the
          beginning...
        </p>
        <p class="mb-8 lg:mb-4 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl">
          Your first subscription was
          <span class="text-green-600">{{ diff_time }}</span> ago.
        </p>
      </div>
      <!-- timeline element start here -->
      <div class="min-h-screen bg-white-100 py-6 flex flex-col justify-center sm:py-12">
        <div class="py-3 sm:max-w-xl sm:mx-auto w-full px-2 sm:px-0">
          <div class="relative text-gray-700 antialiased text-sm font-semibold">
            <!-- Vertical bar running through middle -->
            <div class="hidden sm:block w-1 bg-green-300 absolute h-full left-1/2 transform -translate-x-1/2"></div>

            <!-- odd even sections, set by justify-start and sm:pr-8 -->
            {% for user_subscription in user_subscriptions %}
            <div class="mt-6 sm:mt-0 sm:mb-12">
              <div class="flex flex-col sm:flex-row items-center">
                <div
                  class="flex w-full mx-auto items-center {{ 'justify-start' if loop.index is odd else 'justify-end' }}">
                  <div class="w-full {{ 'sm:w-1/2 sm:pr-8' if loop.index is odd else 'sm:w-1/2 sm:pl-8' }}">
                    <div class="p-4 bg-white rounded shadow">
                      <h3 class="flex items-center mb-1 text-lg text-gray-500 dark:text-white">
                        {{ user_subscription.channel_title }}
                      </h3>
                      <time class="block text-sm font-normal leading-none text-gray-400 dark:text-gray-500">Subscribed
                        on {{
                        user_subscription.subscribed_at.strftime('%d/%m/%Y') }}</time>
                    </div>
                  </div>
                </div>
                <div
                  class="rounded-full bg-blue-500 border-white border-4 w-8 h-8 absolute left-1/2 -translate-y-4 sm:translate-y-0 transform -translate-x-1/2 flex items-center justify-center">
                  <img class="h-6 w-6 rounded-full object-cover" src="{{ user_subscription.thumbnail_default_url }}" />
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <!-- timeline element end here -->
      {% endblock %}
    </section>
  </section>
</div>